### ISSUE TITLE
error on small geo profile page

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#257]
e.g. http://beta.datausa.io/profile/geo/highland-lakes-nj/

From the site-logs:

Traceback (most recent call last):
  File "/home/deploy/Envs/datausa-site/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/deploy/datausa-site/datausa/profile/views.py", line 52, in profile
    p = Profile(attr_data["id"], attr_type)
  File "/home/deploy/datausa-site/datausa/profile/profile.py", line 43, in __init__
    self.splash = Section(self.load_yaml(self.open_file("splash")), self)
  File "/home/deploy/datausa-site/datausa/profile/profile.py", line 279, in load_yaml
    config = self.parse_stats(config)
  File "/home/deploy/datausa-site/datausa/profile/profile.py", line 426, in parse_stats
    string = string.replace(u"<<{}>>".format(k), val)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by jspeis** [comment]
fixed by adding in missing name_long
