### ISSUE TITLE
beverly hills, ca profile causes site error

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-site#802]
### Current Behavior

`/profile/geo/beverly-hills-ca` never loads noticed this error in the site logs:

```
Jan 28 15:05:40 quiincy npm[504554]: Error! TypeError: Cannot read property 'toFixed' of null
Jan 28 15:05:40 quiincy npm[504554]:     at Object.eval (<anonymous>:5:32)
Jan 28 15:05:40 quiincy npm[504554]:     at Object.eval (<anonymous>:3:54)
Jan 28 15:05:40 quiincy npm[504554]:     at sourceString.replace (/home/deploy/datausa-site/utils/varSwap.js:22:17)
Jan 28 15:05:40 quiincy npm[504554]:     at RegExp.[Symbol.replace] (<anonymous>:null:null)
Jan 28 15:05:40 quiincy npm[504554]:     at String.replace (<anonymous>:null:null)
Jan 28 15:05:40 quiincy npm[504554]:     at module.exports (/home/deploy/datausa-site/utils/varSwap.js:11:31)
Jan 28 15:05:40 quiincy npm[504554]:     at varSwapRecursive (/home/deploy/datausa-site/utils/varSwapRecursive.js:33:21)
Jan 28 15:05:40 quiincy npm[504554]:     at obj.(anonymous function).obj.(anonymous function).filter.map.o (/home/deploy/datausa-site/utils/varSwapRecursive.js:37:56)
Jan 28 15:05:40 quiincy npm[504554]:     at Array.map (<anonymous>:null:null)
Jan 28 15:05:40 quiincy npm[504554]:     at varSwapRecursive (/home/deploy/datausa-site/utils/varSwapRecursive.js:37:47)
Jan 28 15:05:40 quiincy npm[504554]:     at obj.(anonymous function).obj.(anonymous function).filter.map.o (/home/deploy/datausa-site/utils/varSwapRecursive.js:37:56)
Jan 28 15:05:40 quiincy npm[504554]:     at Array.map (<anonymous>:null:null)
Jan 28 15:05:40 quiincy npm[504554]:     at varSwapRecursive (/home/deploy/datausa-site/utils/varSwapRecursive.js:37:47)
Jan 28 15:05:40 quiincy npm[504554]:     at obj.(anonymous function).obj.(anonymous function).filter.map.o (/home/deploy/datausa-site/utils/varSwapRecursive.js:37:56)
Jan 28 15:05:40 quiincy npm[504554]:     at Array.map (<anonymous>:null:null)
Jan 28 15:05:40 quiincy npm[504554]:     at varSwapRecursive (/home/deploy/datausa-site/utils/varSwapRecursive.js:37:47)
Jan 28 15:05:40 quiincy npm[504554]:     at Promise.all.then.then.resp (/home/deploy/datausa-site/api/mortarRoute.js:260:25)
Jan 28 15:05:40 quiincy npm[504554]:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to Reproduce (for bugs)

1. `/profile/geo/beverly-hills-ca` ... eventually page times out

**Comment by cnavarreteliz** [comment]
@davelandry can you check in the DB the section where we're using `.toFixed()` please?

**Comment by davelandry** [comment]
fixed! added a `null` catch to the `AbbreviateBig` formatter. looks like this may be the same bug as the Lowell, MA page?

**Comment by cnavarreteliz** [comment]
This bug was solved fixing `AbbreviateBig` formatter, now the profile is working ^^
